# Generated by Django 3.2.6 on 2021-09-24 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_1', models.TextField(verbose_name='Абзац_1')),
                ('image_1', models.ImageField(blank=True, upload_to=news.models.upload_to_detail, verbose_name='Зображення до абзацу 1')),
                ('paragraph_2', models.TextField(blank=True, verbose_name='Абзац_2')),
                ('image_2', models.ImageField(blank=True, upload_to=news.models.upload_to_detail, verbose_name='Зображення до абзацу 2')),
                ('paragraph_3', models.TextField(blank=True, verbose_name='Абзац_3')),
                ('image_3', models.ImageField(blank=True, upload_to=news.models.upload_to_detail, verbose_name='Зображення до абзацу 3')),
                ('paragraph_4', models.TextField(blank=True, verbose_name='Абзац_4')),
                ('image_4', models.ImageField(blank=True, upload_to=news.models.upload_to_detail, verbose_name='Зображення до абзацу')),
                ('paragraph_5', models.TextField(blank=True, verbose_name='Абзац_5')),
                ('image_5', models.ImageField(blank=True, upload_to=news.models.upload_to_detail, verbose_name='Зображення до абзацу 5')),
                ('paragraph_6', models.TextField(blank=True, verbose_name='Абзац_6')),
                ('image_6', models.ImageField(blank=True, upload_to=news.models.upload_to_detail, verbose_name='Зображення до абзацу 6')),
                ('paragraph_7', models.TextField(blank=True, verbose_name='Абзац_7')),
                ('image_7', models.ImageField(blank=True, upload_to=news.models.upload_to_detail, verbose_name='Зображення до абзацу 7')),
                ('paragraph_8', models.TextField(blank=True, verbose_name='Абзац_8')),
                ('image_8', models.ImageField(blank=True, upload_to=news.models.upload_to_detail, verbose_name='Зображення до абзацу 8')),
                ('paragraph_9', models.TextField(blank=True, verbose_name='Абзац_9')),
                ('image_9', models.ImageField(blank=True, upload_to=news.models.upload_to_detail, verbose_name='Зображення до абзацу 9')),
                ('paragraph_10', models.TextField(blank=True, verbose_name='Абзац_10')),
                ('image_10', models.ImageField(blank=True, upload_to=news.models.upload_to_detail, verbose_name='Зображення до абзацу 10')),
                ('paragraph_11', models.TextField(blank=True, verbose_name='Абзац_11')),
                ('image_11', models.ImageField(blank=True, upload_to=news.models.upload_to_detail, verbose_name='Зображення до абзацу 11')),
                ('paragraph_12', models.TextField(blank=True, verbose_name='Абзац_12')),
                ('image_12', models.ImageField(blank=True, upload_to=news.models.upload_to_detail, verbose_name='Зображення до абзацу 12')),
                ('paragraph_13', models.TextField(blank=True, verbose_name='Абзац_13')),
                ('image_13', models.ImageField(blank=True, upload_to=news.models.upload_to_detail, verbose_name='Зображення до абзацу 13')),
                ('paragraph_14', models.TextField(blank=True, verbose_name='Абзац_14')),
                ('image_14', models.ImageField(blank=True, upload_to=news.models.upload_to_detail, verbose_name='Зображення до абзацу 14')),
            ],
            options={
                'ordering': ('-paragraph_1',),
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ('-last_name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('categories',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, upload_to=news.models.upload_to, verbose_name="Зображення до статті')")),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Опубліковано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Змінено')),
                ('status', models.BooleanField(verbose_name='Публікувати')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL, verbose_name='Публікував')),
                ('paragraphs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.articledetail')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
