# Generated by Django 3.2.6 on 2021-09-25 17:18

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='image_1',
            field=models.ImageField(blank=True, default='', upload_to=news.models.upload_to_detail, verbose_name='Зображення до абзацу 1'),
        ),
    ]
