# Generated by Django 3.2.6 on 2021-09-25 17:23

from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articledetail_image_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='news.author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='news.category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='paragraphs',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='news.articledetail'),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='image_1',
            field=models.ImageField(blank=True, upload_to=news.models.upload_to_detail, verbose_name='Зображення до абзацу 1'),
        ),
    ]
