# Generated by Django 3.2.6 on 2021-09-27 01:00

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(default='gallery/default.jpg', upload_to=gallery.models.upload_to, verbose_name='Завантаження фото')),
                ('description', models.CharField(default='', max_length=256, verbose_name='Опис фото')),
                ('topic', models.CharField(default='', max_length=32, verbose_name='Тематика')),
            ],
            options={
                'verbose_name': 'Gallery',
                'ordering': ['date'],
            },
        ),
    ]
