# Generated by Django 3.2.6 on 2021-09-27 01:27

import advertising.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Замовити рекламу', max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=100, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Реклама',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, default='', upload_to=advertising.models.upload_to_audio, verbose_name='Аудіо файл')),
                ('video', models.CharField(blank=True, default='', max_length=256, verbose_name='Відео файл')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Опубліковано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Змінено')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('status', models.BooleanField(verbose_name='Публікувати')),
                ('advertising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='advertising.advertising')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to=settings.AUTH_USER_MODEL, verbose_name='Публікував')),
            ],
            options={
                'verbose_name': 'Приклади реклами',
                'ordering': ['audio'],
            },
        ),
    ]
