# Generated by Django 3.2.6 on 2021-09-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertising',
            options={'ordering': ['title'], 'verbose_name': 'Заголовок', 'verbose_name_plural': 'Заголовок реклами'},
        ),
        migrations.AlterModelOptions(
            name='example',
            options={'ordering': ['created'], 'verbose_name': 'Приклади реклами', 'verbose_name_plural': 'Приклади реклами'},
        ),
        migrations.AddField(
            model_name='example',
            name='description',
            field=models.CharField(default='Замовити рекламу', max_length=100, verbose_name='Заголовок'),
        ),
    ]
