# Generated by Django 3.2.6 on 2021-09-27 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import programs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_auto_20210926_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=100, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, upload_to=programs.models.upload_to_images, verbose_name="Зображення до програми')")),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='news.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='news.category')),
            ],
            options={
                'ordering': ('-title',),
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Кількість переглядів')),
                ('audio_file', models.FileField(blank=True, upload_to=programs.models.upload_to_audio, verbose_name='Аудіо файл')),
                ('description', models.TextField(blank=True, verbose_name='Опис до випуску')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Опубліковано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Змінено')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('status', models.BooleanField(verbose_name='Публікувати')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to=settings.AUTH_USER_MODEL, verbose_name='Публікував')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='programs.program')),
            ],
            options={
                'ordering': ('-description',),
            },
        ),
    ]
