# Generated by Django 3.2.6 on 2021-09-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Назва колективу')),
                ('music_styles', models.CharField(default='', max_length=100, verbose_name='Музичний стиль')),
                ('about_band', models.TextField(default='', verbose_name='Інформація про колектив')),
                ('logo', models.ImageField(upload_to='music_band', verbose_name='Логотип')),
                ('instagram_link', models.CharField(blank=True, default='', max_length=256, verbose_name='Посилання на Instagram')),
                ('facebook_link', models.CharField(blank=True, default='', max_length=256, verbose_name='Посилання на FaceBook')),
                ('youtube_link', models.CharField(blank=True, default='', max_length=256, verbose_name='Посилання на Youtube')),
                ('telegram_link', models.CharField(blank=True, default='', max_length=128, verbose_name='Посилання на Telegram')),
                ('soundcloud_link', models.CharField(blank=True, default='', max_length=128, verbose_name='Посилання на SoundCloud')),
                ('mobile_number', models.CharField(blank=True, default='', max_length=16, verbose_name='Номер телефону')),
                ('email_band', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('last_songs_link_1', models.CharField(blank=True, default='', max_length=256, verbose_name='Реліз_1')),
                ('last_songs_link_2', models.CharField(blank=True, default='', max_length=256, verbose_name='Реліз_2')),
                ('last_songs_link_3', models.CharField(blank=True, default='', max_length=256, verbose_name='Реліз_3')),
                ('last_songs_link_4', models.CharField(blank=True, default='', max_length=256, verbose_name='Реліз_4')),
                ('last_songs_link_5', models.CharField(blank=True, default='', max_length=256, verbose_name='Реліз_5')),
                ('last_songs_link_6', models.CharField(blank=True, default='', max_length=256, verbose_name='Реліз_6')),
                ('last_songs_link_7', models.CharField(blank=True, default='', max_length=256, verbose_name='Реліз_7')),
                ('last_songs_link_8', models.CharField(blank=True, default='', max_length=256, verbose_name='Реліз_8')),
            ],
            options={
                'verbose_name': 'Music band',
                'ordering': ['name'],
            },
        ),
    ]
